export enum TipoExtra {
  SERVICIO = 'SERVICIO',
  ACTIVIDAD = 'ACTIVIDAD',
  EQUIPAMIENTO = 'EQUIPAMIENTO',
  ALIMENTACION = 'ALIMENTACION',
  SEGURO = 'SEGURO',
  ENTRADA_TURISTICA = 'ENTRADA_TURISTICA',
  BEBIDAS = 'BEBIDAS',
  SOUVENIR = 'SOUVENIR',
  TRANSPORTE_ADICIONAL = 'TRANSPORTE_ADICIONAL',
}
