export enum AlimentacionPaquete {
  NINGUNA = 'NINGUNA',
  DESAYUNO = 'DESAYUNO',
  ALMUERZO = 'ALMUERZO',
  CENA = 'CENA',
  MEDIA_PENSION = 'MEDIA_PENSION',
  PENSION_COMPLETA = 'PENSION_COMPLETA',
  TODO_INCLUIDO = 'TODO_INCLUIDO',
}
