export enum EmpresaTransporte {
  BOA = 'BOA',
  TRANS_COPACABANA = 'TRANS_COPACABANA',
  TITICACA = 'TITICACA',
  NUEVA_AMERICANA = 'NUEVA_AMERICANA',
  VIAJES_OFICIAL = 'VIAJES_OFICIAL',
  CUESTAS = 'CUESTAS',
  AMAZONAS = 'AMAZONAS',
  BOLIVAR = 'BOLIVAR',
  EL_SALVADOR = 'EL_SALVADOR',
  FLORIDA = 'FLORIDA',
  PANAMERICANA = 'PANAMERICANA',
  OTRO = 'OTRO',
}
